theme: jekyll-theme-cayman
title: FrUITeR </br> A Framework for Evaluating UI Test Reuse
description: "This website describes FrUITeR's artifacts. If you have any question, feel free to reach out! :)" | "Contact: Yixue Zhao (yixue.zhao [AT] usc.edu)"
markdown: kramdown
